# Generated by Django 5.0 on 2024-01-20 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_batch_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_appointment',
            name='event_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
