# Generated by Django 5.0 on 2024-01-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_batch_appointment_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='course',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='batch_appointment',
            name='event_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
