# Generated by Django 5.0 on 2024-01-21 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appointment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_appointment',
            name='course',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
