# Generated by Django 5.0 on 2024-01-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_batch_appointment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_appointment',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
