# Generated by Django 5.0 on 2024-01-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_appointment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
