# Generated by Django 5.0 on 2024-01-21 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_appointment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_appointment',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
